version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: db-container
    environment:
      MYSQL_DATABASE: franquicias
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-container
    depends_on:
      - mysql-db
    ports:
      - "9191:9191"
    command: ["/wait-for-it.sh", "mysql-db:3306", "--timeout=60", "--", "java", "-jar", "app.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/franquicias
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
